### ISSUE TITLE
Add New EV Predicates 

### ISSUE THREAD

**Issue by xuchef** [themicklepickle/ASP#2]
## Add emergency vehicle (EV) predicates*
\* all predicates refer to the leading EV among all lanes controlled by a traffic light (TL)

### EV Traffic Density
The number of cars in between the EV and the intersection (queue length) divided by the distance between the EV and the intersection.

### EV Distance to Intersection
The distance between the EV and the intersection.

## TODO

- [x] Create functions to retrieve predicate parameters from SUMO
- [x] Add EV predicates to the predicate set
- [x] Change routes config file to include EVs
