### ISSUE TITLE
Tune EV Predicate Values

### ISSUE THREAD

**Issue by xuchef** [themicklepickle/ASP#3]
## TODO
- [x] find optimal bins for the predicate values (can only be done after learning has been modified)
- [x] add approach direction predicate
- [x] make EV predicates conditional (maybe not neccessary)
